<?php

namespace ERPBundle\Repository;

/**
 * AppsenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppsenseRepository extends \Doctrine\ORM\EntityRepository
{
}
