<?php

namespace ERPBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EtablissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtablissementRepository extends EntityRepository
{

    public function getEtablissementByTypeQueryBuilder($id)
    {
        return $this
            ->createQueryBuilder('e')
            ->where('e.typeEtablissement = :id')
            ->setParameter('id', $id);
    }
}
