<?php

namespace ERPBundle\Repository;

/**
 * SliceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliceRepository extends \Doctrine\ORM\EntityRepository
{
}
