<?php

namespace ERPBundle\Repository;

/**
 * SpecialiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialiteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEtablissementByTypeQueryBuilder($id)
    {
        return $this
            ->createQueryBuilder('e')
            ->where('e.Etablissement = :id')
            ->setParameter('id', $id);
    }
}
