<?php

namespace ERPBundle\Repository;

/**
 * UniteEnseignementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UniteEnseignementRepository extends \Doctrine\ORM\EntityRepository
{
}
