examen_index:
    path:     /
    defaults: { _controller: ERPBundle:Front/Enseignant/Examen:index }
    methods:  GET

examen_show:
    path:     /{id}/show
    defaults: { _controller: ERPBundle:Front/Enseignant/Examen:show }
    methods:  GET

examen_new:
    path:     /new
    defaults: { _controller: ERPBundle:Front/Enseignant/Examen:new }
    methods:  [GET, POST]

examen_edit:
    path:     /{id}/edit
    defaults: { _controller: ERPBundle:Front/Enseignant/Examen:edit }
    methods:  [GET, POST]

examen_delete:
    path:     /{id}/delete
    defaults: { _controller: ERPBundle:Front/Enseignant/Examen:delete }
    methods:  DELETE

examen_note:
    path:     /{id}/affecter/note
    defaults: { _controller: ERPBundle:Front/Enseignant/Examen:affecte }
    methods:  [GET, POST]

examen_deleteExamen:
    path:     /{id}/delete
    defaults: { _controller: ERPBundle:Front/Enseignant/Examen:deleteExamen }
    methods:  [GET, POST]