semestre_index:
    path:     /
    defaults: { _controller: ERPBundle:Front/Enseignant/Semestre:index }
    methods:  GET

semestre_show:
    path:     /{id}/show
    defaults: { _controller: ERPBundle:Front/Enseignant/Semestre:show }
    methods:  GET

semestre_new:
    path:     /new
    defaults: { _controller: ERPBundle:Front/Enseignant/Semestre:new }
    methods:  [GET, POST]

semestre_edit:
    path:     /{id}/edit
    defaults: { _controller: ERPBundle:Front/Enseignant/Semestre:edit }
    methods:  [GET, POST]

semestre_delete:
    path:     /{id}/delete
    defaults: { _controller: ERPBundle:Front/Enseignant/Semestre:delete }
    methods:  DELETE
