session_index:
    path:     /
    defaults: { _controller: ERPBundle:Admin/Session:index }
    methods:  GET

session_show:
    path:     /{id}/show
    defaults: { _controller: ERPBundle:Admin/Session:show }
    methods:  GET

session_new:
    path:     /new
    defaults: { _controller: ERPBundle:Admin/Session:new }
    methods:  [GET, POST]

session_edit:
    path:     /{id}/edit
    defaults: { _controller: ERPBundle:Admin/Session:edit }
    methods:  [GET, POST]

session_delete:
    path:     /{id}/delete
    defaults: { _controller: ERPBundle:Admin/Session:delete }
    methods:  DELETE
