<?php

namespace Proxies\__CG__\ERPBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Slice extends \ERPBundle\Entity\Slice implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'ERPBundle\\Entity\\Slice' . "\0" . 'id', '' . "\0" . 'ERPBundle\\Entity\\Slice' . "\0" . 'title', '' . "\0" . 'ERPBundle\\Entity\\Slice' . "\0" . 'total', '' . "\0" . 'ERPBundle\\Entity\\Slice' . "\0" . 'montant', '' . "\0" . 'ERPBundle\\Entity\\Slice' . "\0" . 'createdAt', '' . "\0" . 'ERPBundle\\Entity\\Slice' . "\0" . 'dateDeb', '' . "\0" . 'ERPBundle\\Entity\\Slice' . "\0" . 'reste', '' . "\0" . 'ERPBundle\\Entity\\Slice' . "\0" . 'state', '' . "\0" . 'ERPBundle\\Entity\\Slice' . "\0" . 'dateFin', 'payments', '' . "\0" . 'ERPBundle\\Entity\\Slice' . "\0" . 'qualified', '' . "\0" . 'ERPBundle\\Entity\\Slice' . "\0" . 'etudiant'];
        }

        return ['__isInitialized__', '' . "\0" . 'ERPBundle\\Entity\\Slice' . "\0" . 'id', '' . "\0" . 'ERPBundle\\Entity\\Slice' . "\0" . 'title', '' . "\0" . 'ERPBundle\\Entity\\Slice' . "\0" . 'total', '' . "\0" . 'ERPBundle\\Entity\\Slice' . "\0" . 'montant', '' . "\0" . 'ERPBundle\\Entity\\Slice' . "\0" . 'createdAt', '' . "\0" . 'ERPBundle\\Entity\\Slice' . "\0" . 'dateDeb', '' . "\0" . 'ERPBundle\\Entity\\Slice' . "\0" . 'reste', '' . "\0" . 'ERPBundle\\Entity\\Slice' . "\0" . 'state', '' . "\0" . 'ERPBundle\\Entity\\Slice' . "\0" . 'dateFin', 'payments', '' . "\0" . 'ERPBundle\\Entity\\Slice' . "\0" . 'qualified', '' . "\0" . 'ERPBundle\\Entity\\Slice' . "\0" . 'etudiant'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Slice $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotal($total)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotal', [$total]);

        return parent::setTotal($total);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotal', []);

        return parent::getTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setQualified($qualified)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQualified', [$qualified]);

        return parent::setQualified($qualified);
    }

    /**
     * {@inheritDoc}
     */
    public function getQualified()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQualified', []);

        return parent::getQualified();
    }

    /**
     * {@inheritDoc}
     */
    public function addPayment(\ERPBundle\Entity\Payment $payment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPayment', [$payment]);

        return parent::addPayment($payment);
    }

    /**
     * {@inheritDoc}
     */
    public function removePayment(\ERPBundle\Entity\Payment $payment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePayment', [$payment]);

        return parent::removePayment($payment);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayments', []);

        return parent::getPayments();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtudiant(\ERPBundle\Entity\Etudiant $etudiant = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtudiant', [$etudiant]);

        return parent::setEtudiant($etudiant);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtudiant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtudiant', []);

        return parent::getEtudiant();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaux($taux)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaux', [$taux]);

        return parent::setTaux($taux);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaux()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaux', []);

        return parent::getTaux();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDeb($dateDeb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDeb', [$dateDeb]);

        return parent::setDateDeb($dateDeb);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDeb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDeb', []);

        return parent::getDateDeb();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFin($dateFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFin', [$dateFin]);

        return parent::setDateFin($dateFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFin', []);

        return parent::getDateFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontant($montant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontant', [$montant]);

        return parent::setMontant($montant);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontant', []);

        return parent::getMontant();
    }

    /**
     * {@inheritDoc}
     */
    public function setReste($reste)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReste', [$reste]);

        return parent::setReste($reste);
    }

    /**
     * {@inheritDoc}
     */
    public function getReste()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReste', []);

        return parent::getReste();
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', [$state]);

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', []);

        return parent::getState();
    }

}
