<?php

namespace Proxies\__CG__\ERPBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cour extends \ERPBundle\Entity\Cour implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'ERPBundle\\Entity\\Cour' . "\0" . 'id', '' . "\0" . 'ERPBundle\\Entity\\Cour' . "\0" . 'nom', '' . "\0" . 'ERPBundle\\Entity\\Cour' . "\0" . 'dateAjoute', '' . "\0" . 'ERPBundle\\Entity\\Cour' . "\0" . 'enabled', '' . "\0" . 'ERPBundle\\Entity\\Cour' . "\0" . 'cour', '' . "\0" . 'ERPBundle\\Entity\\Cour' . "\0" . 'classe', '' . "\0" . 'ERPBundle\\Entity\\Cour' . "\0" . 'enseignant', '' . "\0" . 'ERPBundle\\Entity\\Cour' . "\0" . 'matiere', '' . "\0" . 'ERPBundle\\Entity\\Cour' . "\0" . 'coursFichier'];
        }

        return ['__isInitialized__', '' . "\0" . 'ERPBundle\\Entity\\Cour' . "\0" . 'id', '' . "\0" . 'ERPBundle\\Entity\\Cour' . "\0" . 'nom', '' . "\0" . 'ERPBundle\\Entity\\Cour' . "\0" . 'dateAjoute', '' . "\0" . 'ERPBundle\\Entity\\Cour' . "\0" . 'enabled', '' . "\0" . 'ERPBundle\\Entity\\Cour' . "\0" . 'cour', '' . "\0" . 'ERPBundle\\Entity\\Cour' . "\0" . 'classe', '' . "\0" . 'ERPBundle\\Entity\\Cour' . "\0" . 'enseignant', '' . "\0" . 'ERPBundle\\Entity\\Cour' . "\0" . 'matiere', '' . "\0" . 'ERPBundle\\Entity\\Cour' . "\0" . 'coursFichier'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cour $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAjoute($dateAjoute)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAjoute', [$dateAjoute]);

        return parent::setDateAjoute($dateAjoute);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAjoute()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAjoute', []);

        return parent::getDateAjoute();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled($enabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', [$enabled]);

        return parent::setEnabled($enabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnabled', []);

        return parent::getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setClasse(\ERPBundle\Entity\Classe $classe = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClasse', [$classe]);

        return parent::setClasse($classe);
    }

    /**
     * {@inheritDoc}
     */
    public function getClasse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClasse', []);

        return parent::getClasse();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnseignant(\ERPBundle\Entity\Enseignant $enseignant = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnseignant', [$enseignant]);

        return parent::setEnseignant($enseignant);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnseignant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnseignant', []);

        return parent::getEnseignant();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatiere(\ERPBundle\Entity\Matiere $matiere = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatiere', [$matiere]);

        return parent::setMatiere($matiere);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatiere()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatiere', []);

        return parent::getMatiere();
    }

    /**
     * {@inheritDoc}
     */
    public function getCoursFichier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoursFichier', []);

        return parent::getCoursFichier();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoursFichier($coursFichier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoursFichier', [$coursFichier]);

        return parent::setCoursFichier($coursFichier);
    }

    /**
     * {@inheritDoc}
     */
    public function getUploadDir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUploadDir', []);

        return parent::getUploadDir();
    }

    /**
     * {@inheritDoc}
     */
    public function getAbsolutRoot()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsolutRoot', []);

        return parent::getAbsolutRoot();
    }

    /**
     * {@inheritDoc}
     */
    public function getWebpath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebpath', []);

        return parent::getWebpath();
    }

    /**
     * {@inheritDoc}
     */
    public function getUploadRoot()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUploadRoot', []);

        return parent::getUploadRoot();
    }

    /**
     * {@inheritDoc}
     */
    public function uploadCour($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'uploadCour', [$id]);

        return parent::uploadCour($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setCour($cour)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCour', [$cour]);

        return parent::setCour($cour);
    }

    /**
     * {@inheritDoc}
     */
    public function getCour()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCour', []);

        return parent::getCour();
    }

}
