<?php

namespace Proxies\__CG__\ERPBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Permission extends \ERPBundle\Entity\Permission implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'ERPBundle\\Entity\\Permission' . "\0" . 'id', '' . "\0" . 'ERPBundle\\Entity\\Permission' . "\0" . 'eDT', '' . "\0" . 'ERPBundle\\Entity\\Permission' . "\0" . 'class', '' . "\0" . 'ERPBundle\\Entity\\Permission' . "\0" . 'ue', '' . "\0" . 'ERPBundle\\Entity\\Permission' . "\0" . 'grh', '' . "\0" . 'ERPBundle\\Entity\\Permission' . "\0" . 'paiment', '' . "\0" . 'ERPBundle\\Entity\\Permission' . "\0" . 'Admin'];
        }

        return ['__isInitialized__', '' . "\0" . 'ERPBundle\\Entity\\Permission' . "\0" . 'id', '' . "\0" . 'ERPBundle\\Entity\\Permission' . "\0" . 'eDT', '' . "\0" . 'ERPBundle\\Entity\\Permission' . "\0" . 'class', '' . "\0" . 'ERPBundle\\Entity\\Permission' . "\0" . 'ue', '' . "\0" . 'ERPBundle\\Entity\\Permission' . "\0" . 'grh', '' . "\0" . 'ERPBundle\\Entity\\Permission' . "\0" . 'paiment', '' . "\0" . 'ERPBundle\\Entity\\Permission' . "\0" . 'Admin'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Permission $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEDT($eDT)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEDT', [$eDT]);

        return parent::setEDT($eDT);
    }

    /**
     * {@inheritDoc}
     */
    public function getEDT()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEDT', []);

        return parent::getEDT();
    }

    /**
     * {@inheritDoc}
     */
    public function setClass($class)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClass', [$class]);

        return parent::setClass($class);
    }

    /**
     * {@inheritDoc}
     */
    public function getClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClass', []);

        return parent::getClass();
    }

    /**
     * {@inheritDoc}
     */
    public function setUe($ue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUe', [$ue]);

        return parent::setUe($ue);
    }

    /**
     * {@inheritDoc}
     */
    public function getUe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUe', []);

        return parent::getUe();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrh($grh)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrh', [$grh]);

        return parent::setGrh($grh);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrh()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrh', []);

        return parent::getGrh();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaiment($paiment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaiment', [$paiment]);

        return parent::setPaiment($paiment);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaiment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaiment', []);

        return parent::getPaiment();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdmin(\ERPBundle\Entity\Admin $admin = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdmin', [$admin]);

        return parent::setAdmin($admin);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdmin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdmin', []);

        return parent::getAdmin();
    }

}
