<?php

namespace Proxies\__CG__\ERPBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UniteEnseignement extends \ERPBundle\Entity\UniteEnseignement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'ERPBundle\\Entity\\UniteEnseignement' . "\0" . 'id', '' . "\0" . 'ERPBundle\\Entity\\UniteEnseignement' . "\0" . 'nom', '' . "\0" . 'ERPBundle\\Entity\\UniteEnseignement' . "\0" . 'etablissement', '' . "\0" . 'ERPBundle\\Entity\\UniteEnseignement' . "\0" . 'annee', '' . "\0" . 'ERPBundle\\Entity\\UniteEnseignement' . "\0" . 'semestre', '' . "\0" . 'ERPBundle\\Entity\\UniteEnseignement' . "\0" . 'niveau', '' . "\0" . 'ERPBundle\\Entity\\UniteEnseignement' . "\0" . 'matiere', '' . "\0" . 'ERPBundle\\Entity\\UniteEnseignement' . "\0" . 'specialite', '' . "\0" . 'ERPBundle\\Entity\\UniteEnseignement' . "\0" . 'enabled', '' . "\0" . 'ERPBundle\\Entity\\UniteEnseignement' . "\0" . 'dateAjoute', '' . "\0" . 'ERPBundle\\Entity\\UniteEnseignement' . "\0" . 'dateModif'];
        }

        return ['__isInitialized__', '' . "\0" . 'ERPBundle\\Entity\\UniteEnseignement' . "\0" . 'id', '' . "\0" . 'ERPBundle\\Entity\\UniteEnseignement' . "\0" . 'nom', '' . "\0" . 'ERPBundle\\Entity\\UniteEnseignement' . "\0" . 'etablissement', '' . "\0" . 'ERPBundle\\Entity\\UniteEnseignement' . "\0" . 'annee', '' . "\0" . 'ERPBundle\\Entity\\UniteEnseignement' . "\0" . 'semestre', '' . "\0" . 'ERPBundle\\Entity\\UniteEnseignement' . "\0" . 'niveau', '' . "\0" . 'ERPBundle\\Entity\\UniteEnseignement' . "\0" . 'matiere', '' . "\0" . 'ERPBundle\\Entity\\UniteEnseignement' . "\0" . 'specialite', '' . "\0" . 'ERPBundle\\Entity\\UniteEnseignement' . "\0" . 'enabled', '' . "\0" . 'ERPBundle\\Entity\\UniteEnseignement' . "\0" . 'dateAjoute', '' . "\0" . 'ERPBundle\\Entity\\UniteEnseignement' . "\0" . 'dateModif'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UniteEnseignement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setClasse($classe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClasse', [$classe]);

        return parent::setClasse($classe);
    }

    /**
     * {@inheritDoc}
     */
    public function getClasse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClasse', []);

        return parent::getClasse();
    }

    /**
     * {@inheritDoc}
     */
    public function setSemestre($semestre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSemestre', [$semestre]);

        return parent::setSemestre($semestre);
    }

    /**
     * {@inheritDoc}
     */
    public function getSemestre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSemestre', []);

        return parent::getSemestre();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtablissement(\ERPBundle\Entity\Etablissement $etablissment = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtablissement', [$etablissment]);

        return parent::setEtablissement($etablissment);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtablissement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtablissement', []);

        return parent::getEtablissement();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpecialite(\ERPBundle\Entity\Specialite $specialite = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpecialite', [$specialite]);

        return parent::setSpecialite($specialite);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpecialite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpecialite', []);

        return parent::getSpecialite();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled($enabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', [$enabled]);

        return parent::setEnabled($enabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnabled', []);

        return parent::getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAjoute($dateAjoute)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAjoute', [$dateAjoute]);

        return parent::setDateAjoute($dateAjoute);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAjoute()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAjoute', []);

        return parent::getDateAjoute();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateModif($dateModif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateModif', [$dateModif]);

        return parent::setDateModif($dateModif);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateModif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateModif', []);

        return parent::getDateModif();
    }

    /**
     * {@inheritDoc}
     */
    public function addMatiere(\ERPBundle\Entity\Matiere $matiere)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMatiere', [$matiere]);

        return parent::addMatiere($matiere);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMatiere(\ERPBundle\Entity\Matiere $matiere)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMatiere', [$matiere]);

        return parent::removeMatiere($matiere);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatiere()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatiere', []);

        return parent::getMatiere();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnee(\ERPBundle\Entity\Annee $annee = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnee', [$annee]);

        return parent::setAnnee($annee);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnee', []);

        return parent::getAnnee();
    }

    /**
     * {@inheritDoc}
     */
    public function setNiveau(\ERPBundle\Entity\Niveau $niveau = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNiveau', [$niveau]);

        return parent::setNiveau($niveau);
    }

    /**
     * {@inheritDoc}
     */
    public function getNiveau()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNiveau', []);

        return parent::getNiveau();
    }

}
