<?php

namespace Proxies\__CG__\ERPBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Classe extends \ERPBundle\Entity\Classe implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'ERPBundle\\Entity\\Classe' . "\0" . 'id', '' . "\0" . 'ERPBundle\\Entity\\Classe' . "\0" . 'nomClass', '' . "\0" . 'ERPBundle\\Entity\\Classe' . "\0" . 'etablissment', '' . "\0" . 'ERPBundle\\Entity\\Classe' . "\0" . 'specialite', '' . "\0" . 'ERPBundle\\Entity\\Classe' . "\0" . 'annee', '' . "\0" . 'ERPBundle\\Entity\\Classe' . "\0" . 'dateAjoute', '' . "\0" . 'ERPBundle\\Entity\\Classe' . "\0" . 'dateModif', '' . "\0" . 'ERPBundle\\Entity\\Classe' . "\0" . 'enabled', '' . "\0" . 'ERPBundle\\Entity\\Classe' . "\0" . 'etudiant', '' . "\0" . 'ERPBundle\\Entity\\Classe' . "\0" . 'niveau', '' . "\0" . 'ERPBundle\\Entity\\Classe' . "\0" . 'cour', '' . "\0" . 'ERPBundle\\Entity\\Classe' . "\0" . 'examen'];
        }

        return ['__isInitialized__', '' . "\0" . 'ERPBundle\\Entity\\Classe' . "\0" . 'id', '' . "\0" . 'ERPBundle\\Entity\\Classe' . "\0" . 'nomClass', '' . "\0" . 'ERPBundle\\Entity\\Classe' . "\0" . 'etablissment', '' . "\0" . 'ERPBundle\\Entity\\Classe' . "\0" . 'specialite', '' . "\0" . 'ERPBundle\\Entity\\Classe' . "\0" . 'annee', '' . "\0" . 'ERPBundle\\Entity\\Classe' . "\0" . 'dateAjoute', '' . "\0" . 'ERPBundle\\Entity\\Classe' . "\0" . 'dateModif', '' . "\0" . 'ERPBundle\\Entity\\Classe' . "\0" . 'enabled', '' . "\0" . 'ERPBundle\\Entity\\Classe' . "\0" . 'etudiant', '' . "\0" . 'ERPBundle\\Entity\\Classe' . "\0" . 'niveau', '' . "\0" . 'ERPBundle\\Entity\\Classe' . "\0" . 'cour', '' . "\0" . 'ERPBundle\\Entity\\Classe' . "\0" . 'examen'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Classe $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomClass($nomClass)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomClass', [$nomClass]);

        return parent::setNomClass($nomClass);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomClass', []);

        return parent::getNomClass();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnee($annee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnee', [$annee]);

        return parent::setAnnee($annee);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnee', []);

        return parent::getAnnee();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAjoute($dateAjoute)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAjoute', [$dateAjoute]);

        return parent::setDateAjoute($dateAjoute);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAjoute()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAjoute', []);

        return parent::getDateAjoute();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateModif($dateModif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateModif', [$dateModif]);

        return parent::setDateModif($dateModif);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateModif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateModif', []);

        return parent::getDateModif();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtablissment(\ERPBundle\Entity\Etablissement $etablissment = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtablissment', [$etablissment]);

        return parent::setEtablissment($etablissment);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtablissment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtablissment', []);

        return parent::getEtablissment();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpecialite(\ERPBundle\Entity\Specialite $specialite = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpecialite', [$specialite]);

        return parent::setSpecialite($specialite);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpecialite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpecialite', []);

        return parent::getSpecialite();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled($enabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', [$enabled]);

        return parent::setEnabled($enabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnabled', []);

        return parent::getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function addEtudiant(\ERPBundle\Entity\Etudiant $etudiant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEtudiant', [$etudiant]);

        return parent::addEtudiant($etudiant);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEtudiant(\ERPBundle\Entity\Etudiant $etudiant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEtudiant', [$etudiant]);

        return parent::removeEtudiant($etudiant);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtudiant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtudiant', []);

        return parent::getEtudiant();
    }

    /**
     * {@inheritDoc}
     */
    public function setNiveau(\ERPBundle\Entity\Niveau $niveau = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNiveau', [$niveau]);

        return parent::setNiveau($niveau);
    }

    /**
     * {@inheritDoc}
     */
    public function getNiveau()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNiveau', []);

        return parent::getNiveau();
    }

    /**
     * {@inheritDoc}
     */
    public function addCour(\ERPBundle\Entity\Cour $cour)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCour', [$cour]);

        return parent::addCour($cour);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCour(\ERPBundle\Entity\Cour $cour)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCour', [$cour]);

        return parent::removeCour($cour);
    }

    /**
     * {@inheritDoc}
     */
    public function getCour()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCour', []);

        return parent::getCour();
    }

    /**
     * {@inheritDoc}
     */
    public function addExaman(\ERPBundle\Entity\Examen $examan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExaman', [$examan]);

        return parent::addExaman($examan);
    }

    /**
     * {@inheritDoc}
     */
    public function removeExaman(\ERPBundle\Entity\Examen $examan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeExaman', [$examan]);

        return parent::removeExaman($examan);
    }

    /**
     * {@inheritDoc}
     */
    public function getExamen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExamen', []);

        return parent::getExamen();
    }

}
