<?php

namespace Proxies\__CG__\ERPBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Matiere extends \ERPBundle\Entity\Matiere implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'id', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'nom', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'coef', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'credit', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'td', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'tp', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'cours', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'dateAjoute', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'dateModif', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'enabled', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'regime', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'examen', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'unite', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'note', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'niveau', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'specialite', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'cour', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'appsense'];
        }

        return ['__isInitialized__', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'id', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'nom', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'coef', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'credit', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'td', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'tp', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'cours', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'dateAjoute', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'dateModif', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'enabled', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'regime', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'examen', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'unite', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'note', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'niveau', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'specialite', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'cour', '' . "\0" . 'ERPBundle\\Entity\\Matiere' . "\0" . 'appsense'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Matiere $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoef($coef)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoef', [$coef]);

        return parent::setCoef($coef);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoef()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoef', []);

        return parent::getCoef();
    }

    /**
     * {@inheritDoc}
     */
    public function setCredit($credit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCredit', [$credit]);

        return parent::setCredit($credit);
    }

    /**
     * {@inheritDoc}
     */
    public function getCredit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCredit', []);

        return parent::getCredit();
    }

    /**
     * {@inheritDoc}
     */
    public function setTd($td)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTd', [$td]);

        return parent::setTd($td);
    }

    /**
     * {@inheritDoc}
     */
    public function getTd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTd', []);

        return parent::getTd();
    }

    /**
     * {@inheritDoc}
     */
    public function setTp($tp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTp', [$tp]);

        return parent::setTp($tp);
    }

    /**
     * {@inheritDoc}
     */
    public function getTp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTp', []);

        return parent::getTp();
    }

    /**
     * {@inheritDoc}
     */
    public function setCours($cours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCours', [$cours]);

        return parent::setCours($cours);
    }

    /**
     * {@inheritDoc}
     */
    public function getCours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCours', []);

        return parent::getCours();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAjoute($dateAjoute)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAjoute', [$dateAjoute]);

        return parent::setDateAjoute($dateAjoute);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAjoute()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAjoute', []);

        return parent::getDateAjoute();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateModif($dateModif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateModif', [$dateModif]);

        return parent::setDateModif($dateModif);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateModif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateModif', []);

        return parent::getDateModif();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled($enabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', [$enabled]);

        return parent::setEnabled($enabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnabled', []);

        return parent::getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnite(\ERPBundle\Entity\UniteEnseignement $unite = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnite', [$unite]);

        return parent::setUnite($unite);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnite', []);

        return parent::getUnite();
    }

    /**
     * {@inheritDoc}
     */
    public function addCour(\ERPBundle\Entity\Cour $cour)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCour', [$cour]);

        return parent::addCour($cour);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCour(\ERPBundle\Entity\Cour $cour)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCour', [$cour]);

        return parent::removeCour($cour);
    }

    /**
     * {@inheritDoc}
     */
    public function getCour()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCour', []);

        return parent::getCour();
    }

    /**
     * {@inheritDoc}
     */
    public function addAppsense(\ERPBundle\Entity\Appsense $appsense)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAppsense', [$appsense]);

        return parent::addAppsense($appsense);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAppsense(\ERPBundle\Entity\Appsense $appsense)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAppsense', [$appsense]);

        return parent::removeAppsense($appsense);
    }

    /**
     * {@inheritDoc}
     */
    public function getAppsense()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAppsense', []);

        return parent::getAppsense();
    }

    /**
     * {@inheritDoc}
     */
    public function setNiveau(\ERPBundle\Entity\Niveau $niveau = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNiveau', [$niveau]);

        return parent::setNiveau($niveau);
    }

    /**
     * {@inheritDoc}
     */
    public function getNiveau()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNiveau', []);

        return parent::getNiveau();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpecialite(\ERPBundle\Entity\Specialite $specialite = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpecialite', [$specialite]);

        return parent::setSpecialite($specialite);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpecialite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpecialite', []);

        return parent::getSpecialite();
    }

    /**
     * {@inheritDoc}
     */
    public function addNote(\ERPBundle\Entity\Note $note)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNote', [$note]);

        return parent::addNote($note);
    }

    /**
     * {@inheritDoc}
     */
    public function removeNote(\ERPBundle\Entity\Note $note)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeNote', [$note]);

        return parent::removeNote($note);
    }

    /**
     * {@inheritDoc}
     */
    public function getNote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNote', []);

        return parent::getNote();
    }

    /**
     * {@inheritDoc}
     */
    public function addExaman(\ERPBundle\Entity\Examen $examan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExaman', [$examan]);

        return parent::addExaman($examan);
    }

    /**
     * {@inheritDoc}
     */
    public function removeExaman(\ERPBundle\Entity\Examen $examan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeExaman', [$examan]);

        return parent::removeExaman($examan);
    }

    /**
     * {@inheritDoc}
     */
    public function getExamen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExamen', []);

        return parent::getExamen();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegime($regime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegime', [$regime]);

        return parent::setRegime($regime);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegime', []);

        return parent::getRegime();
    }

}
